all : clean generator0 generator1 generator2 generator3 generator4 generator5 generator6 generator7 generator8 generator9 cleano

generator0.o: generator0.cc
	g++ -Wall -c -std=c++11 generator0.cc -o generator0.o

generator0: generator0.o
	g++ -Wall generator0.o -o generator0

generator1.o: generator1.cc
	g++ -Wall -c -std=c++11 generator1.cc -o generator1.o

generator1: generator1.o
	g++ -Wall generator1.o -o generator1

generator2.o: generator2.cc
	g++ -Wall -c -std=c++11 generator2.cc -o generator2.o

generator2: generator2.o
	g++ -Wall generator2.o -o generator2

generator3.o: generator3.cc
	g++ -Wall -c -std=c++11 generator3.cc -o generator3.o

generator3: generator3.o
	g++ -Wall generator3.o -o generator3

generator4.o: generator4.cc
	g++ -Wall -c -std=c++11 generator4.cc -o generator4.o

generator4: generator4.o
	g++ -Wall generator4.o -o generator4

generator5.o: generator5.cc
	g++ -Wall -c -std=c++11 generator5.cc -o generator5.o

generator5: generator5.o
	g++ -Wall generator5.o -o generator5

generator6.o: generator6.cc
	g++ -Wall -c -std=c++11 generator6.cc -o generator6.o

generator6: generator6.o
	g++ -Wall generator6.o -o generator6

generator7.o: generator7.cc
	g++ -Wall -c -std=c++11 generator7.cc -o generator7.o

generator7: generator7.o
	g++ -Wall generator7.o -o generator7

generator8.o: generator8.cc
	g++ -Wall -c -std=c++11 generator8.cc -o generator8.o

generator8: generator8.o
	g++ -Wall generator8.o -o generator8

generator9.o: generator9.cc
	g++ -Wall -c -std=c++11 generator9.cc -o generator9.o

generator9: generator9.o
	g++ -Wall generator9.o -o generator9

cleano:
	rm -f *.o

clean :
	rm -f *.o generator0 generator1 generator2 generator3 generator4 generator5 generator6 generator7 generator8 generator9
